/* Licensed under LGPL v. 2.1 or any later version;
 see GNU LGPL for details.
 Original Author: Jin Chen */

package geovista.common.classification;

import java.util.List;

public interface ClassificationResultItf extends ClassificationResult {

	public CategoryItf getCategory(int index);

	public Category2D getCategory(int x, int y);

	/**
	 * A categoryList contain categories, each of which generated by
	 * classification made based on a dimension ( or attribute)
	 * 
	 * @return
	 */
	public List getAllCategoryLists();

	/**
	 * Get all categories. In case of bi-var classification, it is the combined
	 * result computed from categories contained in categorylist. e.g.:
	 * categorylist1 has 3 categories and categorylist2 has 4 categories,
	 * combined result should have 3*4=12 categories
	 * 
	 * @return
	 */
	public CategoryItf[] getCategories();
}
